#!/bin/bash
HERE="$( dirname "$( readlink -f "$0" )" )"
APPNAME=con
PIDFILE="$HERE/$APPNAME.pid"
PYTHON=$HERE/env/bin/python3
PYTEST=$HERE/env/bin/py.test
LOG=$HERE/log

NUMLOGS=10

cd $HERE

case "$1" in
    env)
        rm -r env
        virtualenv -p python3 env
        $PYTHON setup.py develop
        ;;
    fastenv)
        if [ ! -f env/bin/python3 ]; then
            >&2 echo "No existing environment found. Use $0 env instead."
            exit 1
        fi
        $PYTHON setup.py develop
        ;;
    build)
        mkdir build 2>/dev/null
        $HERE/env/bin/pex . -m backy2.backy:main -o build/backy
        ;;
    clean)
        rm build/backy
        rm -r $HOME/.pex
        ;;
    test)
        $PYTEST -vv
        ;;
    *)
        cat >&2 << EOF
usage: $0 <command>

commands:
   env          Create virtualenv
   fastenv      update existing virtualenv
EOF
        exit 3
        ;;
esac


