"""Store nonce in db too

Revision ID: 30349b678801
Revises: 5260034b8125
Create Date: 2020-04-26 21:33:56.734001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30349b678801'
down_revision = '5260034b8125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('enc_nonce', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'enc_nonce')
    # ### end Alembic commands ###
