"""Added encryption information to blocks

Revision ID: 5260034b8125
Revises: 85966fcda5e6
Create Date: 2020-04-24 17:51:54.807035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5260034b8125'
down_revision = '85966fcda5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('enc_envkey', sa.String(length=80), nullable=True))
    op.add_column('blocks', sa.Column('enc_version', sa.Integer(), nullable=True))
    op.execute("UPDATE blocks SET enc_version=0")
    op.alter_column('blocks', 'enc_version', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'enc_version')
    op.drop_column('blocks', 'enc_envkey')
    # ### end Alembic commands ###
