"""Added expire to versions

Revision ID: 828da0fbbe8d
Revises: 29c655b78818
Create Date: 2019-12-30 12:14:08.747926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828da0fbbe8d'
down_revision = '29c655b78818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('expire', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'expire')
    # ### end Alembic commands ###
