"""Create table stats.

Revision ID: 85966fcda5e6
Revises: 9e0939e3bc6d
Create Date: 2020-04-15 10:17:59.248156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85966fcda5e6'
down_revision = '9e0939e3bc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_uid', sa.String(length=36), nullable=True),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('version_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('version_size_blocks', sa.BigInteger(), nullable=False),
    sa.Column('bytes_read', sa.BigInteger(), nullable=False),
    sa.Column('blocks_read', sa.BigInteger(), nullable=False),
    sa.Column('bytes_written', sa.BigInteger(), nullable=False),
    sa.Column('blocks_written', sa.BigInteger(), nullable=False),
    sa.Column('bytes_found_dedup', sa.BigInteger(), nullable=False),
    sa.Column('blocks_found_dedup', sa.BigInteger(), nullable=False),
    sa.Column('bytes_sparse', sa.BigInteger(), nullable=False),
    sa.Column('blocks_sparse', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_version_uid'), 'stats', ['version_uid'], unique=False)
    # ### end Alembic commands ###
    op.execute("""insert into stats (
        date,
        version_uid,
        version_name,
        version_size_bytes,
        version_size_blocks,
        bytes_read,
        blocks_read,
        bytes_written,
        blocks_written,
        bytes_found_dedup,
        blocks_found_dedup,
        bytes_sparse,
        blocks_sparse,
        duration_seconds
        ) select
            date,
            version_uid,
            version_name,
            version_size_bytes,
            version_size_blocks,
            bytes_read,
            blocks_read,
            bytes_written,
            blocks_written,
            bytes_found_dedup,
            blocks_found_dedup,
            bytes_sparse,
            blocks_sparse,
            duration_seconds
            from stats_old
        """)
    op.drop_table('stats_old')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
