"""expire is datetime now

Revision ID: cd3f15ae79f8
Revises: 828da0fbbe8d
Create Date: 2019-12-31 11:06:31.124057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3f15ae79f8'
down_revision = '828da0fbbe8d'
branch_labels = None
depends_on = None

# TODO: sqlite does not support type changes...

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='versions', column_name='expire', type_=sa.DateTime(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='versions', column_name='expire', type_=sa.Date(), nullable=True)
    # ### end Alembic commands ###
