#!/bin/bash
set -xueo pipefail
VERSION="$(maint-scripts/git-pep440-version)"
exec docker build \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg VCS_URL="$(git config --get remote.origin.url)" \
  --build-arg VERSION="$VERSION" \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .
